### ISSUE TITLE
Fix this error please. 

### ISSUE THREAD

**Issue by YuraKril** [nickurt/zf-bugsnag#5]
Argument 1 passed to ZfBugsnag\Service\BugsnagService::sendException() must be an instance of Exception, instance of Error given, called in **vendor/nickurt/zf-bugsnag

**Comment by nickurt** [comment]
You are using ZF2 or ZF3?

**Comment by YuraKril** [comment]
I use Zend Framework 2 version 2.5.3.

**Comment by nickurt** [comment]
I have some more questions for you;

- Did you manually triggered this in your application or did Zend this?
- What is the PHP-version you are running? 

I will look into this problem this week ...

**Comment by YuraKril** [comment]
Error occurs in zf-bugsnag Mobule.php:
`$eventManager->attach(MvcEvent::EVENT_DISPATCH_ERROR, function ($event) use ..`

I use PHP 7.1

Thank you for your help

**Comment by nickurt** [comment]
Sorry, but this repo is now archived and read-only.
